# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DnDForm.ui'
#
# Created: Sat Mar  7 17:50:55 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(702, 677)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.createMonsterButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createMonsterButton.sizePolicy().hasHeightForWidth())
        self.createMonsterButton.setSizePolicy(sizePolicy)
        self.createMonsterButton.setObjectName(_fromUtf8("createMonsterButton"))
        self.verticalLayout.addWidget(self.createMonsterButton)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(-1)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mobSelect = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mobSelect.sizePolicy().hasHeightForWidth())
        self.mobSelect.setSizePolicy(sizePolicy)
        self.mobSelect.setMaximumSize(QtCore.QSize(200, 16777215))
        self.mobSelect.setObjectName(_fromUtf8("mobSelect"))
        self.horizontalLayout.addWidget(self.mobSelect)
        self.addMobButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addMobButton.sizePolicy().hasHeightForWidth())
        self.addMobButton.setSizePolicy(sizePolicy)
        self.addMobButton.setObjectName(_fromUtf8("addMobButton"))
        self.horizontalLayout.addWidget(self.addMobButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.encounter = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.encounter.sizePolicy().hasHeightForWidth())
        self.encounter.setSizePolicy(sizePolicy)
        self.encounter.setMinimumSize(QtCore.QSize(400, 150))
        self.encounter.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.encounter.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.encounter.setDragEnabled(False)
        self.encounter.setDragDropOverwriteMode(False)
        self.encounter.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.encounter.setAlternatingRowColors(True)
        self.encounter.setCornerButtonEnabled(False)
        self.encounter.setObjectName(_fromUtf8("encounter"))
        self.encounter.setColumnCount(7)
        self.encounter.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.encounter.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.encounter.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.encounter.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.encounter.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.encounter.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.encounter.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.encounter.setHorizontalHeaderItem(6, item)
        self.encounter.horizontalHeader().setCascadingSectionResizes(False)
        self.encounter.horizontalHeader().setDefaultSectionSize(60)
        self.encounter.horizontalHeader().setSortIndicatorShown(False)
        self.encounter.verticalHeader().setDefaultSectionSize(27)
        self.encounter.verticalHeader().setMinimumSectionSize(10)
        self.verticalLayout.addWidget(self.encounter)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.hitValue = QtGui.QSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hitValue.sizePolicy().hasHeightForWidth())
        self.hitValue.setSizePolicy(sizePolicy)
        self.hitValue.setObjectName(_fromUtf8("hitValue"))
        self.gridLayout_2.addWidget(self.hitValue, 0, 0, 1, 2)
        self.damageButton = QtGui.QPushButton(self.groupBox)
        self.damageButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.damageButton.sizePolicy().hasHeightForWidth())
        self.damageButton.setSizePolicy(sizePolicy)
        self.damageButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.damageButton.setCheckable(False)
        self.damageButton.setFlat(False)
        self.damageButton.setObjectName(_fromUtf8("damageButton"))
        self.gridLayout_2.addWidget(self.damageButton, 3, 0, 1, 1)
        self.healButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.healButton.sizePolicy().hasHeightForWidth())
        self.healButton.setSizePolicy(sizePolicy)
        self.healButton.setObjectName(_fromUtf8("healButton"))
        self.gridLayout_2.addWidget(self.healButton, 3, 1, 1, 1)
        self.hitDescription = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hitDescription.sizePolicy().hasHeightForWidth())
        self.hitDescription.setSizePolicy(sizePolicy)
        self.hitDescription.setObjectName(_fromUtf8("hitDescription"))
        self.gridLayout_2.addWidget(self.hitDescription, 1, 0, 1, 2)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.effectButton = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.effectButton.sizePolicy().hasHeightForWidth())
        self.effectButton.setSizePolicy(sizePolicy)
        self.effectButton.setObjectName(_fromUtf8("effectButton"))
        self.gridLayout.addWidget(self.effectButton, 7, 0, 1, 2)
        self.checkBox_11 = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_11.sizePolicy().hasHeightForWidth())
        self.checkBox_11.setSizePolicy(sizePolicy)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.gridLayout.addWidget(self.checkBox_11, 4, 1, 1, 1)
        self.checkBox_12 = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_12.sizePolicy().hasHeightForWidth())
        self.checkBox_12.setSizePolicy(sizePolicy)
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.gridLayout.addWidget(self.checkBox_12, 5, 1, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout.addWidget(self.checkBox_2, 0, 0, 1, 1)
        self.checkBox_10 = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_10.sizePolicy().hasHeightForWidth())
        self.checkBox_10.setSizePolicy(sizePolicy)
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.gridLayout.addWidget(self.checkBox_10, 3, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 1, 0, 1, 1)
        self.checkBox_5 = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_5.sizePolicy().hasHeightForWidth())
        self.checkBox_5.setSizePolicy(sizePolicy)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.gridLayout.addWidget(self.checkBox_5, 4, 0, 1, 1)
        self.checkBox_8 = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_8.sizePolicy().hasHeightForWidth())
        self.checkBox_8.setSizePolicy(sizePolicy)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.gridLayout.addWidget(self.checkBox_8, 1, 1, 1, 1)
        self.checkBox_6 = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_6.sizePolicy().hasHeightForWidth())
        self.checkBox_6.setSizePolicy(sizePolicy)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.gridLayout.addWidget(self.checkBox_6, 5, 0, 1, 1)
        self.checkBox_9 = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_9.sizePolicy().hasHeightForWidth())
        self.checkBox_9.setSizePolicy(sizePolicy)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.gridLayout.addWidget(self.checkBox_9, 2, 1, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout.addWidget(self.checkBox_3, 2, 0, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout.addWidget(self.checkBox_4, 3, 0, 1, 1)
        self.checkBox_7 = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_7.sizePolicy().hasHeightForWidth())
        self.checkBox_7.setSizePolicy(sizePolicy)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.gridLayout.addWidget(self.checkBox_7, 0, 1, 1, 1)
        self.checkBox_13 = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.gridLayout.addWidget(self.checkBox_13, 6, 0, 1, 2)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.mobInfo = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mobInfo.sizePolicy().hasHeightForWidth())
        self.mobInfo.setSizePolicy(sizePolicy)
        self.mobInfo.setMinimumSize(QtCore.QSize(0, 150))
        self.mobInfo.setMaximumSize(QtCore.QSize(16777215, 250))
        self.mobInfo.setObjectName(_fromUtf8("mobInfo"))
        self.verticalLayout.addWidget(self.mobInfo)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.battleLog = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.battleLog.sizePolicy().hasHeightForWidth())
        self.battleLog.setSizePolicy(sizePolicy)
        self.battleLog.setBaseSize(QtCore.QSize(150, 0))
        self.battleLog.setProperty("isWrapping", True)
        self.battleLog.setWordWrap(True)
        self.battleLog.setObjectName(_fromUtf8("battleLog"))
        self.horizontalLayout_3.addWidget(self.battleLog)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 702, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.createMonsterButton.setText(_translate("MainWindow", "Create Monster", None))
        self.addMobButton.setText(_translate("MainWindow", "Add mob", None))
        self.encounter.setSortingEnabled(False)
        item = self.encounter.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Health", None))
        item = self.encounter.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Max HP", None))
        item = self.encounter.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Recharge", None))
        item = self.encounter.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status 1", None))
        item = self.encounter.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status 2", None))
        item = self.encounter.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Status 3", None))
        item = self.encounter.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Status 4", None))
        self.groupBox.setTitle(_translate("MainWindow", "Damage and Healing", None))
        self.damageButton.setText(_translate("MainWindow", "Damage", None))
        self.healButton.setText(_translate("MainWindow", "Heal", None))
        self.hitDescription.setPlaceholderText(_translate("MainWindow", "Description", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Status Effects", None))
        self.effectButton.setText(_translate("MainWindow", "Set Conditions", None))
        self.checkBox_11.setText(_translate("MainWindow", "Restrained", None))
        self.checkBox_12.setText(_translate("MainWindow", "Stunned", None))
        self.checkBox_2.setText(_translate("MainWindow", "Blinded", None))
        self.checkBox_10.setText(_translate("MainWindow", "Prone", None))
        self.checkBox.setText(_translate("MainWindow", "Charmed", None))
        self.checkBox_5.setText(_translate("MainWindow", "Incapacitated", None))
        self.checkBox_8.setText(_translate("MainWindow", "Petrified", None))
        self.checkBox_6.setText(_translate("MainWindow", "Incorporeal", None))
        self.checkBox_9.setText(_translate("MainWindow", "Poisoned", None))
        self.checkBox_3.setText(_translate("MainWindow", "Frightened", None))
        self.checkBox_4.setText(_translate("MainWindow", "Grappled", None))
        self.checkBox_7.setText(_translate("MainWindow", "Paralyzed", None))
        self.checkBox_13.setText(_translate("MainWindow", "Recharge", None))
        self.mobInfo.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.Helvetica Neue DeskInterface\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Dragon</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">AC: 26</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">STR</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CON<br />DEX</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">INT</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CHA</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">WIS</p></body></html>", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionSave.setText(_translate("MainWindow", "Save...", None))
        self.actionLoad.setText(_translate("MainWindow", "Load...", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))

